// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcc6EXXqsAMjBTnIN1ITRLhLe6PtlOo_o',
    appId: '1:161593984792:web:f87238c3744ab77d32406d',
    messagingSenderId: '161593984792',
    projectId: 'estufa-iot-25a96',
    authDomain: 'estufa-iot-25a96.firebaseapp.com',
    storageBucket: 'estufa-iot-25a96.firebasestorage.app',
    measurementId: 'G-C5Y5VH2X9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0BKRVR7hbHMadjB4Bd8p9RHZLCh8XNuI',
    appId: '1:161593984792:android:be5ec12902d47e1332406d',
    messagingSenderId: '161593984792',
    projectId: 'estufa-iot-25a96',
    storageBucket: 'estufa-iot-25a96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_D4IBOgReDVcjaJeszkfpC_AtJpCLcS4',
    appId: '1:161593984792:ios:f6a4dd626fa4130032406d',
    messagingSenderId: '161593984792',
    projectId: 'estufa-iot-25a96',
    storageBucket: 'estufa-iot-25a96.firebasestorage.app',
    iosBundleId: 'com.example.dashboardEstufaIot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_D4IBOgReDVcjaJeszkfpC_AtJpCLcS4',
    appId: '1:161593984792:ios:f6a4dd626fa4130032406d',
    messagingSenderId: '161593984792',
    projectId: 'estufa-iot-25a96',
    storageBucket: 'estufa-iot-25a96.firebasestorage.app',
    iosBundleId: 'com.example.dashboardEstufaIot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcc6EXXqsAMjBTnIN1ITRLhLe6PtlOo_o',
    appId: '1:161593984792:web:7e05d24fd61d625b32406d',
    messagingSenderId: '161593984792',
    projectId: 'estufa-iot-25a96',
    authDomain: 'estufa-iot-25a96.firebaseapp.com',
    storageBucket: 'estufa-iot-25a96.firebasestorage.app',
    measurementId: 'G-7RNKNH80WF',
  );
}
